CREATE TABLE order(
	orderId INT UNSIGNED NOT NULL AUTO_INCREMENT,
	orderPrice FLOAT UNSIGNED NOT NULL,
	deliveryBid FLOAT UNSIGNED NOT NULL,
	description VARCHAR(1024) NOT NULL,
	location VARCHAR (256) NOT NULL,
	phoneNumber VARCHAR (10) NOT NULL
);